[tool.poetry]
name = "gitbugactions"
version = "3.0.0"
description = "A tool that builds bug-fix benchmarks by leveraging GitHub Actions."
authors = ["Nuno Saavedra <nuno.saavedra@tecnico.ulisboa.pt>", "Andr√© Silva <andreans@kth.se>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
PyGithub = "2.3.0"
pandas = "2.2.2"
pygit2 = "1.15.0"
PyYAML = "6.0.1"
psutil = "6.0.0"
docker = "7.1.0"
unidiff = "0.7.5"
tqdm = "4.66.4"
urllib3 = "2.2.2"
junitparser = "3.1.2"
fire = "0.6.0"
nltk = "3.8.1"
attrs = "^23.2.0"
referencing = "^0.35.1"
pytest-ordering = "^0.6"
numpy = "2.0.0"
schedule = "^1.2.2"
jsonschema = "^4.23.0"

[tool.poetry.group.dev.dependencies]
pytest = "8.2.2"
pytest-mock = "3.14.0"
pytest-dependency = "0.6.0"
flaky = "3.8.1"
pytest-ignore-flaky = "2.2.1"
black = "24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
