[tool.poetry]
name = "gitbugactions"
version = "2.0.1"
description = "A tool that builds bug-fix benchmarks by leveraging GitHub Actions."
authors = ["Nuno Saavedra <nuno.saavedra@tecnico.ulisboa.pt>", "Andr√© Silva <andreans@kth.se>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
PyGithub = "1.58.1"
pandas = "1.5.3"
pygit2 = "1.12.1"
PyYAML = "6.0.0"
psutil = "5.9.5"
docker = "5.0.3"
unidiff = "0.7.5"
tqdm = "4.65.0"
urllib3 = "1.26.5"
junitparser = "3.1.0"
fire = "0.5.0"
nltk = "3.8.1"

[tool.poetry.group.dev.dependencies]
pytest = "7.3.1"
pytest-mock = "3.10.0"
pytest-dependency = "0.5.1"
flaky = "3.7.0"
pytest-ignore-flaky = "2.0.0"
black = "23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
